apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java
  template:
    metadata:
      labels:
        app: my-java
    spec:
      containers:
      - name: my-java
        image: 060067310822.dkr.ecr.ap-northeast-2.amazonaws.com/simple-java-app:20
        ports:
        - containerPort: 8080